---
title: "Jellybelly Diversity"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW
Analayze data from non-random sampling of Jellybelly jellybeans from a seven year-old kid in a candy store

See https://github.com/QuantitativeBiodiversity/QB-2017/tree/master/Week2-Alpha

## 1) SETUP

### A. Retrieve and Set Your Working Directory

```{r, results = 'hide'}
rm(list = ls())
getwd()
setwd("~/GitHub/jellybelly")
```

### B. Load data

```{r}
# morophotype = visual description
# id = best guess based Jelly Belly flavor guide: https://www.jellybelly.com/flavor-guides
# mass = weight (g) of all beans in sample belonging to morphotype plus Dixie cup weight
# count = number of beans in a sample belonging to morphotype

jb <- read.table("jellybelly.2020.txt", sep = "\t", header = TRUE)

# mass of Dixie cup
#dixie.mass <- 2

# remove mass of Dixie cup
#mass.cor <- jb.raw$mass - dixie.mass
#jb <- data.frame(jb.raw[, 1:3], mass.cor, jb.raw[, 4])
colnames(jb)[2] <- "count"
```

## 2) DIVERSITY CALCULATIONS

```{r}
# Total abundance (N)
sum(jb$count)

# Observed richness
S.obs <- function(x = ""){
  rowSums(x > 0) * 1
}

S.obs(t(jb$count))

# Coverage
coverage <- function(x = ""){
  1 - (sum(x == 1) / rowSums(x))
  }

coverage(t(jb$count)) 

# Esimated richness with Chao1
S.chao1 <- function(x = ""){
  S.obs(x) + (sum(x == 1)^2) / (2 * sum(x == 2))
}

S.chao1(t(jb$count))

# Visualize rank abundance curve
RAC <- function(x = ""){
  x = as.vector(x)
  x.ab = x[x > 0]
  x.ab.ranked = x.ab[order(x.ab, decreasing = TRUE)]
  return(x.ab.ranked)
  }

plot.new()
site1 <- t(jb$count)

rac <- RAC(x = site1)
ranks <- as.vector(seq(1, length(rac)))
opar <- par(no.readonly = TRUE)                       # Saves default plot parameters
par(mar = c(5.1, 5.1, 4.1, 2.1))                      # New settings for par
plot(ranks, log(rac), type = 'p', axes = F,           # Plots w/o axes
     xlab = "Rank in abundance", ylab = "Abundance",
     las = 1, cex.lab = 1.4, cex.axis = 1.25)

box()                                                 # Manually adds border
axis(side = 1, labels = T, cex.axis = 1.25)           # Manually adds X-axis
axis(side = 2, las = 1, cex.axis = 1.25,              # Manually adds Log-Scaled Y-axis
     labels = c(1, 2, 5, 10, 20, 50), at = log(c(1, 2, 5, 10, 20, 50)))

par <- opar                                           # Resets plotting parameters

# Smith and Wilson's Evenness Index (Evar)
Evar <- function(x){
  x <- as.vector(x[x > 0])
  1 - (2/pi)*atan(var(log(x)))
  }

Evar(t(jb[,5]))

# Shannon's Diversity (H')
ShanH <- function(x = ""){
  H = 0
  for (n_i in x){
    if(n_i > 0) {
      p = n_i / sum(x)
      H = H - p*log(p) 
    }
  }
  return(H)
}

ShanH(t(jb[,5]))
```


